"""empty message

Revision ID: 86efbb69c5ba
Revises: 
Create Date: 2025-04-18 18:33:49.134648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86efbb69c5ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_Camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=50), nullable=False),
    sa.Column('camera_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_RoadClosure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=50), nullable=False),
    sa.Column('closure_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_TrafficData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('time_from', sa.String(length=5), nullable=True),
    sa.Column('time_to', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_User',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('login')
    )
    op.create_table('T_Feedback',
    sa.Column('feedbackID', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['T_User.userID'], ),
    sa.PrimaryKeyConstraint('feedbackID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_Feedback')
    op.drop_table('T_User')
    op.drop_table('T_TrafficData')
    op.drop_table('T_RoadClosure')
    op.drop_table('T_Camera')
    # ### end Alembic commands ###
