"""initial migration

Revision ID: a85a3d200cc1
Revises: 
Create Date: 2025-04-15 12:26:14.132899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85a3d200cc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_TrafficData')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_TrafficData',
    sa.Column('dataID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('routeID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trafficStatus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accidents', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routeID'], ['T_Route.routeID'], name='T_TrafficData_routeID_fkey'),
    sa.PrimaryKeyConstraint('dataID', name='T_TrafficData_pkey')
    )
    # ### end Alembic commands ###
