"""Fix relationships

Revision ID: bde54c59c944
Revises: a85a3d200cc1
Create Date: 2025-04-16 11:33:57.456197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde54c59c944'
down_revision = 'a85a3d200cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_TrafficData',
    sa.Column('dataID', sa.Integer(), nullable=False),
    sa.Column('routeID', sa.Integer(), nullable=True),
    sa.Column('trafficStatus', sa.String(), nullable=False),
    sa.Column('accidents', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['routeID'], ['T_Route.routeID'], ),
    sa.PrimaryKeyConstraint('dataID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_TrafficData')
    # ### end Alembic commands ###
